/*  TUDO ISSO RETORNA BOOLEAN: TRUE OU FALSE
    >   MAIOR
    <   MENOR
    >=  MAIOR IGUAL
    <=  MENOR IGUAL
    =   ATRIBUICAO
    ==  COMPARAR IGUALDADE DE VALORES
    === COMPARAR IGUALDADE DE VALORES E TIPOS
    !=  DIFERENTE
    !   NEGACAO
*/